# Generated by Django 3.2 on 2021-04-20 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.CharField(db_index=True, max_length=50)),
                ('team_name', models.TextField(db_index=True, max_length=50)),
            ],
            options={
                'ordering': ['team_name'],
            },
        ),
    ]
